### PR TITLE
DEV-4416: Integrate Siklu unit tests to: github.com/siklu/pyangbind/tree/master/tests

### PR DESCRIPTION
**Pull request by eduardpo**
## Description
Support for Siklu pyangbind/tests,
Unit tests framework used for testing pyangbind functionality.

## Tests
tests/serialise/xml-deserialise/run_siklu.py
pybindIETFXMLEncoder() & pybindIETFXMLDecoder() validation using Siklu YANG input.

## References
JIRA: DEV-4416

### CODE REVIEW

**Comment by eduardpo** [comment]
The fork include changes required for Siklu netconf automation

**Comment by shmuelhazan** [comment]
Can you add more descrtiption? Also, what has been tested here?

**Review by eduardpo — COMMENTED** [review]
Up

**Review by eduardpo — COMMENTED** [review]
Up

**Comment by shmuelhazan** [comment]
The description is unclear. Also, there are some duplicate commits with the other PR. can you drop them?

**Comment by eduardpo** [comment]
> The description is unclear. Also, there are some duplicate commits with the other PR. can you drop them?
@shmuelhazan 
May be it will be easier now to drop PR, and create it again after the previous one is completed...?

**Review by eduardpo — COMMENTED** [review]
Up

**Pull request merged**
